server:
  port: 8056

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

# DataBase 연결 정보
spring:
  datasource:
    # MySQL 일 경우 com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
#    JDBC 연결일때 사용
#    jdbc-url=jdbc: mariadb://localhost:3306/example_db?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    # JPA 연결일때 사용
    url: jdbc:mariadb://localhost:3306/example_db?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: 6h5g4f#D@S!A
  jpa:
    generate-ddl: true
    # true 설정시 JPA 쿼리문 확인 가능
    show-sql: true
    # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
        format_sql: true